name: Java CI with Maven

on:
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Test with Maven
        run: mvn -B test --file pom.xml
      - name: Build Docker image
        run: docker build -t hello-app .
      - name: Verify endpoint
        run: |
          docker run -d -p 8080:8080 --name test-app hello-app
          sleep 10
          curl -s http://localhost:8080/api/hello | grep "Hello"
          docker stop test-app
          docker rm test-app